### ISSUE TITLE
Update does not preserve state

### ISSUE THREAD

**Issue by Mr-Headrick** [LandonB5/reactapp3#6]
You must re-enter all the data or it is lost.

**Comment by LandonB5** [comment]
I'll work on this once I get the main branch back to a working state, specifically I can create recipes and events.

**Comment by LandonB5** [comment]
I began working on this however im having an issue getting it to display still

**Comment by LandonB5** [comment]
Instead of using generate client I am going to go back to using your approach but trying to fix it.

**Comment by LandonB5** [comment]
Now works but still has a few minor issues
